# -*- coding: utf-8 -*-
"""YoutubeDownloader_byLeo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l-ScJMZb9N4RonCZ8e3d2lcjlzHc2Idd

**DESCARGAR CANCIONES ESPECÍFICAS DIRECTAMENTE AL EQUIPO**
"""

# INSTALAR DEPENDENCIAS
!pip install yt-dlp pydub

# INSTALAR FFMPEG
!apt-get install ffmpeg -y

# IMPORTAR LIBRERÍAS
import os
from yt_dlp import YoutubeDL
from pydub import AudioSegment
from google.colab import files

# CONFIGURAR FFMPEG
AudioSegment.converter = '/usr/bin/ffmpeg'
AudioSegment.ffprobe = '/usr/bin/ffprobe'

# FUNCIÓN PARA DESCARGAR AUDIOS
def download_youtube_audio_to_mp3(urls, download_folder):
    if not os.path.exists(download_folder):
        os.makedirs(download_folder)

    ydl_opts = {
        'format': 'bestaudio/best',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
        'outtmpl': os.path.join(download_folder, '%(title)s.%(ext)s'),
        'quiet': True,
        'noplaylist': True
    }

    with YoutubeDL(ydl_opts) as ydl:
        for url in urls:
            try:
                print(f"Descargando {url}...")
                ydl.download([url])
                print("Descarga y conversión completada.")

                # Obtener el nombre del archivo convertido
                info_dict = ydl.extract_info(url, download=False)
                filename = ydl.prepare_filename(info_dict).replace('.webm', '.mp3').replace('.m4a', '.mp3')

                # Descargar el archivo al equipo local
                files.download(filename)
            except Exception as e:
                print(f"Error descargando {url}: {e}")

# LISTA DE URLs A DESCARGAR
urls_texto = """
https://youtu.be/LVce-8YhEGs?list=RD9sHyVWQykVw
https://youtu.be/Y2Vnjmb2gFs?list=RD9g5uDIg378o
"""

# PROCESAR LAS URLs Y EJECUTAR LA FUNCIÓN
urls = urls_texto.strip().split('\n')
download_folder = '/content/Descargas'
download_youtube_audio_to_mp3(urls, download_folder)

"""**DESCARGAR PLAYLIST COMPLETAS DIRECTAMENTE AL EQUIPO**"""

# iNSTALAR DEPENDENCIAS
!pip install yt-dlp pydub

# INSTALAR FFMPEG
!apt-get install ffmpeg

# IMPORTAR LIBRERÍAS
import os
from yt_dlp import YoutubeDL
from pydub import AudioSegment
from google.colab import files

# CONFIGURAR FFMPEG
AudioSegment.converter = '/usr/bin/ffmpeg'
AudioSegment.ffprobe = '/usr/bin/ffprobe'

# FUNCIÓN PARA DESCARGAR AUDIOS
def download_youtube_audio_to_mp3(urls, download_folder):
    if not os.path.exists(download_folder):
        os.makedirs(download_folder)

    ydl_opts = {
        'format': 'bestaudio/best',
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
        'outtmpl': os.path.join(download_folder, '%(title)s.%(ext)s'),
        'quiet': True,
    }

    with YoutubeDL(ydl_opts) as ydl:
        for url in urls:
            try:
                print(f"Descargando {url}...")
                ydl.download([url])
                print("Descarga y conversión completada.")

                # Obtén el nombre del archivo descargado
                info_dict = ydl.extract_info(url, download=False)
                filename = ydl.prepare_filename(info_dict).replace('.webm', '.mp3').replace('.m4a', '.mp3')

                # Descargar el archivo MP3 a la computadora local
                files.download(filename)
            except Exception as e:
                print(f"Error descargando {url}: {e}")

# LISTA DE URLs A DESCARGAR
urls_texto = """
https://youtu.be/LVce-8YhEGs?list=RD9sHyVWQykVw
https://youtu.be/Y2Vnjmb2gFs?list=RD9g5uDIg378o
"""

# PROCESAR LAS URLs Y EJECUTAR LA FUNCIÓN
urls = urls_texto.strip().split('\n')
download_folder = '/content/Descargas'
download_youtube_audio_to_mp3(urls, download_folder)